version: '3'
services:
  cinema_project:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000" 
    depends_on:
      - shop_data
  shop_data:
    image: 'postgres:14'
    environment:
      POSTGRES_DB: shop_api_db
      POSTGRES_USER: shop_api_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - 'data:/var/lib/postgresql/data'
volumes:
  data: